### ISSUE TITLE
Client side filtering feature lost in Release 2.0

### ISSUE THREAD

**Issue by jessemcdowell-AI** [dsternlicht/RESTool#88]
The client-side filtering feature (introduced by https://github.com/dsternlicht/RESTool/pull/47) is missing in Release 2.0, but it's still referenced in the documentation (`filterable` field, https://github.com/dsternlicht/RESTool#display-fields).

**Comment by jessemcdowell-AI** [comment]
In 2.0.4, I see this error in the console when trying to use the client-side filter:

```
TypeError: e[a].toLowerCase is not a function
    at page.comp.tsx:256
    at Array.forEach (<anonymous>)
    at page.comp.tsx:255
    at Array.filter (<anonymous>)
    at page.comp.tsx:253
    at page.comp.tsx:314
    at page.comp.tsx:353
```

**Comment by dsternlicht** [comment]
> In 2.0.4, I see this error in the console when trying to use the client-side filter:
> 
> ```
> TypeError: e[a].toLowerCase is not a function
>     at page.comp.tsx:256
>     at Array.forEach (<anonymous>)
>     at page.comp.tsx:255
>     at Array.filter (<anonymous>)
>     at page.comp.tsx:253
>     at page.comp.tsx:314
>     at page.comp.tsx:353
> ```

Fixed on: https://github.com/dsternlicht/RESTool/commit/a597ca1863eb40031620ba9e4051735a42d89ffe
